### ISSUE TITLE
What is the latest version?

### ISSUE THREAD

**Issue by wingedonezero** [JorenSix/SyncSink#1]
I found this using google. Which lead me to your site https://0110.be/Software. It states 1.0 on github but on your site it says 1.5. are these the same or is the one on your site the latest?

**Comment by JorenSix** [comment]
Hi 
The version of the repository is indeed the most recent. The version indicator is off. 

Note that this is also available now:

https://0110.be/posts/SyncSink.wasm_-_Synchronize_media_files_by_audio-to-audio_alignment

Regards

Joren
